version: '3.8'

services:
  debug_app:
    container_name: todo_app_debug
    build:
      context: .
      target: debug
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=todo_app/app.py
      - FLASK_ENV=development
