version: '3.8'

services:
  dev_app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=todo_app/app.py
      - FLASK_ENV=development
    command: poetry run flask run --host=0.0.0.0 --reload
