name: Docker Test Workflow

on:
  push:
    paths-ignore:
    - 'README.md'

  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker Image for Testing
      run: docker build --target test -t todo_app_test .

    - name: Run Tests in Docker
      run: docker run --rm todo_app_test

    - name: Copy Test Results
      run: docker cp todo_app_test-container:/app/test-results.xml .

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: test-results.xml
